### PR TITLE
Adding Dockerfile for Container Build

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add a Dockerfile to support development with containers, specifically Docker (although this needs connecting to the video device) and much easier, [Singularity containers](https://www.sylabs.io/guides/3.0/user-guide/installation.html). 

@amzeratul - I ran the basic tests, and not knowing anything else about game development, wanted to ask for your suggestions for a good "starter project" to test the engine using the container? Thanks muchly!

### CODE REVIEW

**Comment by vsoch** [comment]
oh one quick note - the container on Docker Hub now is missing pciutils - it takes a long time to build so I can ping you when it's ready to test.

**Comment by amzeratul** [comment]
Hi @vsoch! Thank you for the contributions!

I'll be happy to merge this, however I don't want the Readme.md file to imply that docker is the standard way to set up the library; this is because video game development is very Visual Studio centric, and it's likely that most people will be interested in the "local build" process. Could you flip those around so the original build instructions come first, and Docker is provided as a convenient alternative for Unix users? (I'm also willing to hear counter-arguments to that if you think I'm wrong here.)

Currently the test projects are not fully working, but there's a separate pull request to fix those. Perhaps those would be a good test once they're working!

**Comment by vsoch** [comment]
This sounds like the right thing to do! I just reorganized, and called it an "experimental setup."

When the PR goes through can you ping me to test the test projects?

**Comment by ParityB1t** [comment]
Might want to update to Disco (Ubuntu 19.04), Disco default package repo does have `boost 1.6.7` and `yaml-cpp-dev 0.6` so don't have to `wget` and compile manually. Managed to compile Halley on that yesterday on WSL

**Comment by vsoch** [comment]
Using a distribution without long term support (LTS) isn't a good idea... I'd suggest waiting for the next LTS for these libraries.

**Comment by ParityB1t** [comment]
> Using a distribution without long term support (LTS) isn't a good idea... I'd suggest waiting for the next LTS for these libraries.

thats fair :P

**Pull request closed without merging**
